### ISSUE TITLE
Python usage question

### ISSUE THREAD

**Issue by raffaeler** [microsoft/xlang#733]
I made the following steps:
```
> pip install winrt
Collecting winrt
  Using cached winrt-1.0.21033.1-cp39-none-win32.whl (4.7 MB)
Installing collected packages: winrt
Successfully installed winrt-1.0.21033.1

> pyclient.py
Traceback (most recent call last):
  File "H:\dev.git\Experiments\InteropExperiments\WinRTNativeHosting\NativeToManaged\PythonClient\pyclient.py", line 2, in <module>
    import winrt.windows.foundation as wf
  File "C:\Users\raffaeler\AppData\Local\Programs\Python\Python39\lib\site-packages\winrt\__init__.py", line 3, in <module>
    from . import _winrt
ImportError: DLL load failed while importing _winrt: %1 is not a valid Win32 application.
```

where the `pyclient.py` is:
```
import winrt.windows.foundation as wf
u = wf.Uri("https://github.com/")
u2 = u.combine_uri("Microsoft/xlang/tree/master/src/tool/python")
print(str(u2))
```

What's wrong?

**Comment by raffaeler** [comment]
Installing `winrt` package from a native x64 cmd works.
The only thing I can imagine is that the package is not marked as architecture specific x86 vs x64 and install the one and only available which is x64.

If that is true, the package has a **bug** and the x86 version will never work.

This means that python projection should be repackaged (possibly with the new wheel and not with egg) in two distinct versions, x86 and x64.
